<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.407.12" />
    <PackageReference Include="AWSSDK.FSx" Version="3.7.403.57" />
    <PackageReference Include="AWSSDK.Glue" Version="3.7.417.2" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.416.27" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="SMBLibrary" Version="1.5.4" />
  </ItemGroup>

</Project>
